# Numpy Exercise

In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.2


### Array Creation
Create a numpy array of size 10, filled with zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Createa numpy array with values ranging from 10 to 49

In [3]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a numpy matrix of 2*2 integers, filled with ones.

In [4]:
np.ones([2,2], dtype=np.int)

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\2225746612.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [5]:
np.ones([3, 2], dtype = np.float)

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\1706469954.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3, 2], dtype = np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [6]:
X = np.arange(4, dtype = np.int)

np.ones_like(X)

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\743733180.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype = np.int)


array([1, 1, 1, 1])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [7]:
X = np.array([[1,2,3],[4,5,6]], dtype=np.int)
X*0
# np.zeros_like(X)

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\120036505.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1,2,3],[4,5,6]], dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

### Create a numpy matrix of 4*4 integers, filled with fivesm

In [8]:
np.ones([4,4], dtype = np.int)*5

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\3070688422.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4], dtype = np.int)*5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens

In [9]:
X = np.array([[1,1],[1,1]], dtype = np.int)
# X*7
np.ones_like(X)*7

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\3163727857.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1,1],[1,1]], dtype = np.int)


array([[7, 7],
       [7, 7]])

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [11]:
np.random.randint(10,size=3)

array([6, 2, 1])

### Given the X python list convert it to an Y numpy array

In [12]:
X = [1, 2, 3, 4, 5]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) #different type

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


### Given the X numpy array, make a copy and store it on Y

In [13]:
X = np.array([2, 4, 6, 8], dtype= np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) #different id

[2 4 6 8] 2324694927952
[2 4 6 8] 2324694928912


C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\281709011.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([2, 4, 6, 8], dtype= np.int)


### Create a numpy array with numbers from 1 to 10

In [14]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

### Create a numpy array with numbers from 1 to 10, in descending order.

In [15]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [16]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Show the memory size of the given Z numpy matrix

In [17]:
Z = np.zeros((2,2))

print("%d bytes" % (Z.size * Z.itemsize))

32 bytes


# Array indexation

### Given the X numpy array, show it's first element

In [18]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

###  Given the X numpy array, show it's last elemen

In [19]:
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

### Given the X numpy array, show it's first three elements

In [20]:
X = np.array(['A','B','C','D','E'])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

### Given the X numpy array, show all middle elements

In [21]:
X = np.array(['A','B','C','D','E'])
# X[1:4]
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

###  Given the X numpy array, show the elements in reverse position

In [22]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

### Given the X numpy array, show the elements in an odd position

In [23]:
X = np.array(['A','B','C','D','E'])
# X[[0, 2, 4]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

### Given the X numpy matrix, show the first row elements and last row

In [24]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[0])
print(X[-1])

[1 2 3 4]
[13 14 15 16]


### Given the X numpy matrix, show the first element on first row

In [25]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0][0]
# X[0, 0]

1

### Given the X numpy matrix, show the last element on last row

In [26]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1][-1]
# X[-1, -1]

16

In [27]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

# X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

### Given the X numpy matrix, show the first two elements on the first two rows

In [28]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

#### Given the X numpy matrix, show the last two elements on the last two rows

In [29]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

# Array manipulation

### Convert the given integer numpy array to float

In [30]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

C:\Users\anshu\AppData\Local\Temp\ipykernel_12764\4247539020.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

### Reverse the given numpy array (first element becomes last)

In [31]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

### Order (sort) the given numpy array

In [32]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

### Given the X numpy array, set the fifth element equal to 1

In [33]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Given the X numpy array, change the 50 with a 40

In [34]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

#### Given the X numpy matrix, change the last row with all 1

In [35]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

### Given the X numpy matrix, change the last item on the last row with a 0

In [36]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-2, -2] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15, 16]])

#### Given the X numpy matrix, add 5 to every element

In [37]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Boolean arrays (also called masks

### Given the X numpy array, make a mask showing negative elements

In [39]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

### Given the X numpy array, get the number greater than 5

In [40]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

### Given the X numpy array, get numbers higher than the elements mean

In [41]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

### Given the X numpy array, get numbers equal to 2 or 10

In [42]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

# Logic functions

### Given the X numpy array, return True if none of its elements is zero

In [43]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

### Given the X numpy array, return True if any of its elements is zero

In [44]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

# Summary statistics

### Given the X numpy array, show the sum of its elements

In [45]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

### Given the X numpy array, show the mean value of its elements

In [46]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

### Given the X numpy matrix, show the sum of its column

In [47]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

### Given the X numpy matrix, show the mean value of its row

In [48]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

### Given the X numpy array, show the max value of its elements

In [49]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10